web:
  host: "127.0.0.1"
  port: "7070"

postgres:
  host: "127.0.0.1"
  port: "5432"
  username: "postgres"
  dbName: "table_res"

fileStorage:
  bucketName: "ez-booking-bucket"
  awsRegion: "eu-north-1"
  aws_access_key: "AKIAULNNH4ARJJVXJXVI"

smtp:
  host: "smtp.gmail.com"
  port: 587
  from: "duman070601@gmail.com"
